CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(16) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          CONSTRAINT uk_user_username UNIQUE (username),
                          CONSTRAINT uk_user_email UNIQUE (email)
);

CREATE INDEX idx_app_user_username ON app_user(username);

CREATE INDEX idx_app_user_email ON app_user(email);